### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by lohithvadde** [suraj-deshmukh/CoWin-Vaccination-Auto-Schedule#1]
I filled in all the details in Config.py and started it.

Receiving this below error.

lohiths-personal-MacBook-Pro:CoWin-Vaccination-Auto-Schedule lohith$ python book.py
  File "book.py", line 9
    print(f"Beneficiaries Status_code: {beneficiaries.status_code}\n{beneficiaries.text}")
                                                                                        ^
SyntaxError: invalid syntax

**Comment by lohithvadde** [comment]
Is the beneficiary id same as the reference id (besides name) showing up in the cowin portal ?

**Comment by suraj-deshmukh** [comment]
yes beneficiary id same as the reference id

**Comment by suraj-deshmukh** [comment]
> I filled in all the details in Config.py and started it.
> 
> Receiving this below error.
> 
> lohiths-personal-MacBook-Pro:CoWin-Vaccination-Auto-Schedule lohith$ python book.py
> File "book.py", line 9
> print(f"Beneficiaries Status_code: {beneficiaries.status_code}\n{beneficiaries.text}")
> ^
> SyntaxError: invalid syntax

Which python version are you using. This will work on python 3

**Comment by lohithvadde** [comment]
yeah. you are right. It is working on Python 3.
