### ISSUE TITLE
getting this error kali linux 

### ISSUE THREAD

**Issue by RSGtechnical** [suraj-deshmukh/CoWin-Vaccination-Auto-Schedule#3]
File "book.py", line 9
    print(f"Beneficiaries Status_code: {beneficiaries.status_code}\n{beneficiaries.text}")
                                                                                        ^
SyntaxError: invalid syntax

**Comment by lohithvadde** [comment]
Which python version are you using. This will work on python 3

**Comment by RSGtechnical** [comment]
3.7.6

**Comment by RSGtechnical** [comment]
can you tell me the correct format to put beneficiaries id in config file 

this is what i did 

Beneficiaries_Ids = { 24139050145880

    '18':["",""],

    '45':[""]

} #beficiary ids in str format

**Comment by suraj-deshmukh** [comment]
put your ids in list. make sure each element of list is str like below.

     Beneficiaries_Ids = { 
          '18':["id1","id2"],
          '45':["id3"]
      }

**Comment by RSGtechnical** [comment]
Beneficiaries_Ids = { 

    '18':["24139050145880","24139050145880"],

    '45':["24139050145880"]

} #beficiary ids in str format

still get the error

**Comment by suraj-deshmukh** [comment]
what is the exact error. please specify exact python version as well. If possible attach screenshot

**Comment by RSGtechnical** [comment]
yes here what i get when i run the script 
![Screenshot 2021-05-10 142829](https://user-images.githubusercontent.com/74641321/117633817-057c9f80-b19c-11eb-889e-1c6fb1b8c23e.jpg)

**Comment by RSGtechnical** [comment]
python version 3.7.6

**Comment by suraj-deshmukh** [comment]
can you show what's being printed when you type python in command prompt

**Comment by RSGtechnical** [comment]
here 
![Screenshot 2021-05-10 145803](https://user-images.githubusercontent.com/74641321/117638116-2646f400-b1a0-11eb-87de-e0c475fd0ea1.jpg)

**Comment by suraj-deshmukh** [comment]
you need python 3.5+ . what you have is python 2.7.12

**Comment by RSGtechnical** [comment]
so how to upgrade as you see i have upgraded the python

**Comment by RSGtechnical** [comment]
yes got the working in kali linux to use python3 you have to tell the linux so now its working
